name: Flutter Nightly Build

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    # 添加JDK设置作为前置步骤
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      # 调用原有工作流
      - name: Run Flutter Build
        uses: ./.github/workflows/flutter-build.yml
        with:
          upload-artifact: true
          upload-tag: "nightly"
